/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-error-selectors.ts
 * Generated at: 2026-02-27T07:57:42.979Z
 * Contracts: 6 ABIs scanned
 * Sources:
 *   - contracts\artifacts\src\base\BaseFlashArbitrage.sol\BaseFlashArbitrage.json
 *   - contracts\artifacts\src\FlashLoanArbitrage.sol\FlashLoanArbitrage.json
 *   - contracts\artifacts\src\BalancerV2FlashArbitrage.sol\BalancerV2FlashArbitrage.json
 *   - contracts\artifacts\src\PancakeSwapFlashArbitrage.sol\PancakeSwapFlashArbitrage.json
 *   - contracts\artifacts\src\SyncSwapFlashArbitrage.sol\SyncSwapFlashArbitrage.json
 *   - contracts\artifacts\src\CommitRevealArbitrage.sol\CommitRevealArbitrage.json
 *
 * To regenerate, run: npm run generate:error-selectors
 *
 * @see base.strategy.ts - parseRevertReason() uses these selectors
 */

// =============================================================================
// Custom Error Selectors
// =============================================================================

/**
 * Mapping of 4-byte error selectors to error names.
 * Selectors are computed as: keccak256(ErrorName(types...)).slice(0, 10)
 */
export const CUSTOM_ERROR_SELECTORS: Record<string, string> = {
  '0x0d35b41e': 'RouterAlreadyApproved', // RouterAlreadyApproved()
  '0x0ed1df6b': 'PoolAlreadyWhitelisted', // PoolAlreadyWhitelisted()
  '0x14203b4b': 'InvalidRouterAddress', // InvalidRouterAddress()
  '0x145718a7': 'CommitmentAlreadyExists', // CommitmentAlreadyExists()
  '0x1b4c7fdf': 'PoolNotWhitelisted', // PoolNotWhitelisted()
  '0x1fedb84a': 'InvalidProtocolAddress', // InvalidProtocolAddress()
  '0x233d278a': 'RouterNotApproved', // RouterNotApproved()
  '0x2641a211': 'InsufficientSlippageProtection', // InsufficientSlippageProtection()
  '0x2c5211c6': 'InvalidAmount', // InvalidAmount()
  '0x33782793': 'InvalidSwapPath', // InvalidSwapPath()
  '0x3472835b': 'SwapPathAssetMismatch', // SwapPathAssetMismatch()
  '0x3a19268b': 'PoolNotFromFactory', // PoolNotFromFactory()
  '0x42301c23': 'InsufficientOutputAmount', // InsufficientOutputAmount()
  '0x4e47f8ea': 'InsufficientProfit', // InsufficientProfit()
  '0x53adc965': 'CommitmentExpired', // CommitmentExpired()
  '0x590eba9c': 'FlashLoanNotActive', // FlashLoanNotActive()
  '0x6bb27929': 'InsufficientPoolLiquidity', // InsufficientPoolLiquidity()
  '0x769d11e4': 'InvalidDeadline', // InvalidDeadline()
  '0x7a58c192': 'InvalidSwapDeadline', // InvalidSwapDeadline()
  '0x86a559ea': 'EmptySwapPath', // EmptySwapPath()
  '0x875d88f5': 'InvalidCommitAge', // InvalidCommitAge()
  '0x889577e8': 'EmptyPoolsArray', // EmptyPoolsArray()
  '0x8f3d672c': 'CommitmentAlreadyRevealed', // CommitmentAlreadyRevealed()
  '0x92111eb2': 'FlashLoanFailed', // FlashLoanFailed()
  '0x98bdb2e0': 'InvalidGasLimit', // InvalidGasLimit()
  '0x9c8d2cd2': 'InvalidRecipient', // InvalidRecipient()
  '0xa83116fc': 'TransactionTooOld', // TransactionTooOld()
  '0xafc5b7cb': 'MultiAssetNotSupported', // MultiAssetNotSupported()
  '0xb12d13eb': 'ETHTransferFailed', // ETHTransferFailed()
  '0xb6682ad2': 'CommitmentNotFound', // CommitmentNotFound()
  '0xbb1cb70b': 'BatchTooLarge', // BatchTooLarge(uint256,uint256)
  '0xc1116db5': 'CommitmentTooRecent', // CommitmentTooRecent()
  '0xc6d3637a': 'UnauthorizedRevealer', // UnauthorizedRevealer()
  '0xd475a053': 'CommitmentNotExpired', // CommitmentNotExpired()
  '0xd924e5f4': 'InvalidOwnerAddress', // InvalidOwnerAddress()
  '0xd92e233d': 'ZeroAddress', // ZeroAddress()
  '0xddd77f0d': 'PathTooLong', // PathTooLong(uint256,uint256)
  '0xe17c49b7': 'InvalidFlashLoanCaller', // InvalidFlashLoanCaller()
  '0xef7cc6b6': 'InvalidFlashLoanInitiator', // InvalidFlashLoanInitiator()
  '0xf3c98916': 'InvalidMinimumProfit', // InvalidMinimumProfit()
};

/**
 * Reverse mapping: error name to selector
 */
export const ERROR_NAME_TO_SELECTOR: Record<string, string> = {
  'RouterAlreadyApproved': '0x0d35b41e',
  'PoolAlreadyWhitelisted': '0x0ed1df6b',
  'InvalidRouterAddress': '0x14203b4b',
  'CommitmentAlreadyExists': '0x145718a7',
  'PoolNotWhitelisted': '0x1b4c7fdf',
  'InvalidProtocolAddress': '0x1fedb84a',
  'RouterNotApproved': '0x233d278a',
  'InsufficientSlippageProtection': '0x2641a211',
  'InvalidAmount': '0x2c5211c6',
  'InvalidSwapPath': '0x33782793',
  'SwapPathAssetMismatch': '0x3472835b',
  'PoolNotFromFactory': '0x3a19268b',
  'InsufficientOutputAmount': '0x42301c23',
  'InsufficientProfit': '0x4e47f8ea',
  'CommitmentExpired': '0x53adc965',
  'FlashLoanNotActive': '0x590eba9c',
  'InsufficientPoolLiquidity': '0x6bb27929',
  'InvalidDeadline': '0x769d11e4',
  'InvalidSwapDeadline': '0x7a58c192',
  'EmptySwapPath': '0x86a559ea',
  'InvalidCommitAge': '0x875d88f5',
  'EmptyPoolsArray': '0x889577e8',
  'CommitmentAlreadyRevealed': '0x8f3d672c',
  'FlashLoanFailed': '0x92111eb2',
  'InvalidGasLimit': '0x98bdb2e0',
  'InvalidRecipient': '0x9c8d2cd2',
  'TransactionTooOld': '0xa83116fc',
  'MultiAssetNotSupported': '0xafc5b7cb',
  'ETHTransferFailed': '0xb12d13eb',
  'CommitmentNotFound': '0xb6682ad2',
  'BatchTooLarge': '0xbb1cb70b',
  'CommitmentTooRecent': '0xc1116db5',
  'UnauthorizedRevealer': '0xc6d3637a',
  'CommitmentNotExpired': '0xd475a053',
  'InvalidOwnerAddress': '0xd924e5f4',
  'ZeroAddress': '0xd92e233d',
  'PathTooLong': '0xddd77f0d',
  'InvalidFlashLoanCaller': '0xe17c49b7',
  'InvalidFlashLoanInitiator': '0xef7cc6b6',
  'InvalidMinimumProfit': '0xf3c98916',
};

/**
 * All known error signatures (for debugging/documentation)
 */
export const ERROR_SIGNATURES: Record<string, string> = {
  'RouterAlreadyApproved': 'RouterAlreadyApproved()',
  'PoolAlreadyWhitelisted': 'PoolAlreadyWhitelisted()',
  'InvalidRouterAddress': 'InvalidRouterAddress()',
  'CommitmentAlreadyExists': 'CommitmentAlreadyExists()',
  'PoolNotWhitelisted': 'PoolNotWhitelisted()',
  'InvalidProtocolAddress': 'InvalidProtocolAddress()',
  'RouterNotApproved': 'RouterNotApproved()',
  'InsufficientSlippageProtection': 'InsufficientSlippageProtection()',
  'InvalidAmount': 'InvalidAmount()',
  'InvalidSwapPath': 'InvalidSwapPath()',
  'SwapPathAssetMismatch': 'SwapPathAssetMismatch()',
  'PoolNotFromFactory': 'PoolNotFromFactory()',
  'InsufficientOutputAmount': 'InsufficientOutputAmount()',
  'InsufficientProfit': 'InsufficientProfit()',
  'CommitmentExpired': 'CommitmentExpired()',
  'FlashLoanNotActive': 'FlashLoanNotActive()',
  'InsufficientPoolLiquidity': 'InsufficientPoolLiquidity()',
  'InvalidDeadline': 'InvalidDeadline()',
  'InvalidSwapDeadline': 'InvalidSwapDeadline()',
  'EmptySwapPath': 'EmptySwapPath()',
  'InvalidCommitAge': 'InvalidCommitAge()',
  'EmptyPoolsArray': 'EmptyPoolsArray()',
  'CommitmentAlreadyRevealed': 'CommitmentAlreadyRevealed()',
  'FlashLoanFailed': 'FlashLoanFailed()',
  'InvalidGasLimit': 'InvalidGasLimit()',
  'InvalidRecipient': 'InvalidRecipient()',
  'TransactionTooOld': 'TransactionTooOld()',
  'MultiAssetNotSupported': 'MultiAssetNotSupported()',
  'ETHTransferFailed': 'ETHTransferFailed()',
  'CommitmentNotFound': 'CommitmentNotFound()',
  'BatchTooLarge': 'BatchTooLarge(uint256,uint256)',
  'CommitmentTooRecent': 'CommitmentTooRecent()',
  'UnauthorizedRevealer': 'UnauthorizedRevealer()',
  'CommitmentNotExpired': 'CommitmentNotExpired()',
  'InvalidOwnerAddress': 'InvalidOwnerAddress()',
  'ZeroAddress': 'ZeroAddress()',
  'PathTooLong': 'PathTooLong(uint256,uint256)',
  'InvalidFlashLoanCaller': 'InvalidFlashLoanCaller()',
  'InvalidFlashLoanInitiator': 'InvalidFlashLoanInitiator()',
  'InvalidMinimumProfit': 'InvalidMinimumProfit()',
};

/**
 * Check if a selector matches a known custom error
 */
export function isKnownErrorSelector(selector: string): boolean {
  return Object.prototype.hasOwnProperty.call(CUSTOM_ERROR_SELECTORS, selector.toLowerCase());
}

/**
 * Get error name from selector (returns undefined if not found)
 */
export function getErrorName(selector: string): string | undefined {
  return CUSTOM_ERROR_SELECTORS[selector.toLowerCase()];
}
