/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-error-selectors.ts
 * Generated at: 2026-02-15T18:05:02.018Z
 * Contract: FlashLoanArbitrage
 * Source: /Users/pho/DEV/Arbitrage_Bot/arbitrage_new/contracts/artifacts/src/FlashLoanArbitrage.sol/FlashLoanArbitrage.json
 *
 * To regenerate, run: npm run generate:error-selectors
 *
 * @see base.strategy.ts - parseRevertReason() uses these selectors
 */

// =============================================================================
// Custom Error Selectors
// =============================================================================

/**
 * Mapping of 4-byte error selectors to error names.
 * Selectors are computed as: keccak256(ErrorName(types...)).slice(0, 10)
 */
export const CUSTOM_ERROR_SELECTORS: Record<string, string> = {
  '0x0d35b41e': 'RouterAlreadyApproved', // RouterAlreadyApproved()
  '0x14203b4b': 'InvalidRouterAddress', // InvalidRouterAddress()
  '0x1fedb84a': 'InvalidProtocolAddress', // InvalidProtocolAddress()
  '0x233d278a': 'RouterNotApproved', // RouterNotApproved()
  '0x2641a211': 'InsufficientSlippageProtection', // InsufficientSlippageProtection()
  '0x2c5211c6': 'InvalidAmount', // InvalidAmount()
  '0x33782793': 'InvalidSwapPath', // InvalidSwapPath()
  '0x3472835b': 'SwapPathAssetMismatch', // SwapPathAssetMismatch()
  '0x42301c23': 'InsufficientOutputAmount', // InsufficientOutputAmount()
  '0x4e47f8ea': 'InsufficientProfit', // InsufficientProfit()
  '0x7a58c192': 'InvalidSwapDeadline', // InvalidSwapDeadline()
  '0x86a559ea': 'EmptySwapPath', // EmptySwapPath()
  '0x9c8d2cd2': 'InvalidRecipient', // InvalidRecipient()
  '0xa83116fc': 'TransactionTooOld', // TransactionTooOld()
  '0xb12d13eb': 'ETHTransferFailed', // ETHTransferFailed()
  '0xd924e5f4': 'InvalidOwnerAddress', // InvalidOwnerAddress()
  '0xddd77f0d': 'PathTooLong', // PathTooLong(uint256,uint256)
  '0xe17c49b7': 'InvalidFlashLoanCaller', // InvalidFlashLoanCaller()
  '0xef7cc6b6': 'InvalidFlashLoanInitiator', // InvalidFlashLoanInitiator()
};

/**
 * Reverse mapping: error name to selector
 */
export const ERROR_NAME_TO_SELECTOR: Record<string, string> = {
  'RouterAlreadyApproved': '0x0d35b41e',
  'InvalidRouterAddress': '0x14203b4b',
  'InvalidProtocolAddress': '0x1fedb84a',
  'RouterNotApproved': '0x233d278a',
  'InsufficientSlippageProtection': '0x2641a211',
  'InvalidAmount': '0x2c5211c6',
  'InvalidSwapPath': '0x33782793',
  'SwapPathAssetMismatch': '0x3472835b',
  'InsufficientOutputAmount': '0x42301c23',
  'InsufficientProfit': '0x4e47f8ea',
  'InvalidSwapDeadline': '0x7a58c192',
  'EmptySwapPath': '0x86a559ea',
  'InvalidRecipient': '0x9c8d2cd2',
  'TransactionTooOld': '0xa83116fc',
  'ETHTransferFailed': '0xb12d13eb',
  'InvalidOwnerAddress': '0xd924e5f4',
  'PathTooLong': '0xddd77f0d',
  'InvalidFlashLoanCaller': '0xe17c49b7',
  'InvalidFlashLoanInitiator': '0xef7cc6b6',
};

/**
 * All known error signatures (for debugging/documentation)
 */
export const ERROR_SIGNATURES: Record<string, string> = {
  'RouterAlreadyApproved': 'RouterAlreadyApproved()',
  'InvalidRouterAddress': 'InvalidRouterAddress()',
  'InvalidProtocolAddress': 'InvalidProtocolAddress()',
  'RouterNotApproved': 'RouterNotApproved()',
  'InsufficientSlippageProtection': 'InsufficientSlippageProtection()',
  'InvalidAmount': 'InvalidAmount()',
  'InvalidSwapPath': 'InvalidSwapPath()',
  'SwapPathAssetMismatch': 'SwapPathAssetMismatch()',
  'InsufficientOutputAmount': 'InsufficientOutputAmount()',
  'InsufficientProfit': 'InsufficientProfit()',
  'InvalidSwapDeadline': 'InvalidSwapDeadline()',
  'EmptySwapPath': 'EmptySwapPath()',
  'InvalidRecipient': 'InvalidRecipient()',
  'TransactionTooOld': 'TransactionTooOld()',
  'ETHTransferFailed': 'ETHTransferFailed()',
  'InvalidOwnerAddress': 'InvalidOwnerAddress()',
  'PathTooLong': 'PathTooLong(uint256,uint256)',
  'InvalidFlashLoanCaller': 'InvalidFlashLoanCaller()',
  'InvalidFlashLoanInitiator': 'InvalidFlashLoanInitiator()',
};

/**
 * Check if a selector matches a known custom error
 */
export function isKnownErrorSelector(selector: string): boolean {
  return selector.toLowerCase() in CUSTOM_ERROR_SELECTORS;
}

/**
 * Get error name from selector (returns undefined if not found)
 */
export function getErrorName(selector: string): string | undefined {
  return CUSTOM_ERROR_SELECTORS[selector.toLowerCase()];
}
