/**
 * Unit Tests for P2 L2-Turbo Partition Service
 *
 * Tests partition-specific configuration, exports, and service setup.
 * The JEST_WORKER_ID guard in index.ts prevents auto-start during import.
 *
 * Common test blocks are generated by the shared partition test factory.
 * Only P2-specific tests (if any) are defined inline below.
 */

import {
  MockUnifiedChainDetector,
  createMockLogger,
  createMockStateManager,
  createCoreMocks,
  createConfigMocks,
} from '@arbitrage/test-utils/mocks/partition-service.mock';
import { generatePartitionUnitTests } from '@arbitrage/test-utils/partition-test-factory';

// =============================================================================
// Mocks - Must be defined before imports
// =============================================================================

const mockLogger = createMockLogger();
const mockStateManager = createMockStateManager();

// FIX #6: Use shared createCoreMocks() to replace ~148 lines of inline mock definitions
jest.mock('@arbitrage/core', () => createCoreMocks(mockLogger, mockStateManager));

// Mock @arbitrage/config with L2-Turbo partition configuration
jest.mock('@arbitrage/config', () => createConfigMocks({
  partitionId: 'l2-turbo',
  name: 'L2 Turbo Chains',
  chains: ['arbitrum', 'optimism', 'base'],
  region: 'asia-southeast1',
  provider: 'fly',
  resourceProfile: 'standard',
  priority: 1,
  maxMemoryMB: 512,
  healthCheckIntervalMs: 10000,
  failoverTimeoutMs: 45000,
  chainsSubset: ['arbitrum', 'optimism', 'base'],
}));

// Use shared MockUnifiedChainDetector from @arbitrage/test-utils
jest.mock('@arbitrage/unified-detector', () => ({
  UnifiedChainDetector: MockUnifiedChainDetector,
}));

// =============================================================================
// Common Tests (generated by partition test factory)
// =============================================================================

generatePartitionUnitTests({
  partitionId: 'l2-turbo',
  partitionLabel: 'P2',
  partitionName: 'L2-Turbo',
  chains: ['arbitrum', 'optimism', 'base'],
  defaultPort: 3002,
  region: 'asia-southeast1',
  exportPrefix: 'P2',
  importModule: () => import('../../src/index'),
  mockLogger,
});
